server:
  port: 8080

logging:
  level:
    root: debug

spring:
  application:
    name: spring-cloud-gateway-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:1234@eureka-server:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: gateway

management:
  endpoints:
    web:
      exposure:
        include: health,info
